### ISSUE TITLE
Package does not have the right structure

### ISSUE THREAD

**Issue by gdalle** [dukeeagle/DZIGA.jl#1]
You should initialize with PkgTemplates (https://github.com/JuliaCI/PkgTemplates.jl) as demonstrated in the lecture on good programming practices

**Comment by gdalle** [comment]
For instance, the Yaml files defining GitHub actions belong in a folder called `.github/workflows/`

**Comment by gdalle** [comment]
Also, setting up the docs is tedious when done manually

**Comment by gdalle** [comment]
And `.gitignore` will need to be beefed up

**Comment by gdalle** [comment]
I think you might find it easier to restart from scratch

**Comment by dukeeagle** [comment]
Will do!

**Comment by dukeeagle** [comment]
3e88455530f9e54a4b1ac0af12baf6d4d3f56aec
