### ISSUE TITLE
Configure GitHub pages

### ISSUE THREAD

**Issue by gdalle** [dukeeagle/DZIGA.jl#3]
The HTML pages are created by the CI process on the `gh-pages` branch, so all you have to do is go to the repository settings, section "Pages" and tell GitHub to build the site from that branch

**Comment by dukeeagle** [comment]
I'm currently using dukeeagle.github.io for another project of mine, so I gotta figure out how to let them both be publicly available. Will report back.

**Comment by gdalle** [comment]
It's gonna be available at `dukeeagle.github.io/DZIGA.jl`

**Comment by dukeeagle** [comment]
Stable still doesn't work, but dev does. Will see if it gets better with time.

**Comment by dukeeagle** [comment]
Docs are fully available here! 

https://www.regressions.net/DZIGA.jl/dev/#DZIGA.greedy_bst-Tuple{HashCode2014.City}
