### ISSUE TITLE
This file does not belong on the repo

### ISSUE THREAD

**Issue by gdalle** [dukeeagle/DZIGA.jl#7]
https://github.com/dukeeagle/DZIGA.jl/blob/254ad2d877eda9db1f3aa9dd442e2502b0f513a7/DZIGA%20FINAL%20PROJECT.code-workspace#L1-L8

It is a local file giving the code editor config for your computer. It would be no use to anyone else working with you on it

**Comment by dukeeagle** [comment]
079ef86a327ec4794efc7a83bab9b877f8f9399b
